### ISSUE TITLE
[Fix request] Specify the Docker container name

### ISSUE THREAD

**Issue by openaging-admin** [openaging/momiji#61]
**Describe the bug**
When creating a Docker container, the container name is not named momiji.

**To Reproduce**
It is named to "docker-app".

**Expected behavior**
When creating a Docker container, explicitly name the container momiji.

**Screenshots**
None

**Additional context**
Edit Docker/docker-compose.yml like below

```
version: '3'
services:
  app:
    build:
      context: ..
      dockerfile: ./Docker/Dockerfile
    image: momiji:latest  #add
    volumes:
      - ../:/app
    command: bash
    container_name: momiji
    tty: true

```
